analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.753
title: "Stuart's Grid"
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8397626748774201
  brandStrength: 0.7062028823420405
  rhythmicContrast: 0.955484950216487
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.8119184272363782
purpose: []
favicon: null
name: stumax
typography_spectrum: 0.31241
